import type { ArtEvent } from '../types/event.types';
import { shiftIsoDate, todayIso } from '@/lib/date';

export const initialEvents: ArtEvent[] = [
  {
    id: 'e1',
    title: 'The Modernist Spirit',
    name_vie: 'Tinh thần Hiện đại',
    name_en: 'The Modernist Spirit',
    organizer: 'Galerie Quynh',
    startDate: todayIso(),
    endDate: shiftIsoDate(30),
    location: 'D1, Ho Chi Minh City',
    city: 'Ho Chi Minh City',
    district: 'District 1',
    lat: 10.7818,
    lng: 106.6994,
    imageUrl: 'https://images.unsplash.com/photo-1494948141550-256616053995?auto=format&fit=crop&q=80&w=1200',
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&q=80&w=1200' },
      { type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-artist-painting-on-a-canvas-4342-large.mp4' },
      { type: 'image', url: 'https://images.unsplash.com/photo-1518998053502-53cc83e9ce38?auto=format&fit=crop&q=80&w=1200' },
    ],
    description:
      'A survey of Vietnamese modernist painting from 1950 to 1980. This exhibition brings together rare archival lacquer works and private collections to tell the story of a nation in flux.',
    category: 'exhibition',
    art_medium: 'Painting',
    event_type: 'Exhibition Opening',
    place_type: 'Gallery',
    tags: ['featured', 'modernism', 'lacquer'],
    address: '65 De Tham, District 1, Ho Chi Minh City',
    google_map_link: 'https://maps.google.com/?q=65+De+Tham+District+1+Ho+Chi+Minh+City',
    saved_count: 91,
    featured: true,
    moderation_status: 'approved',
  },
  {
    id: 'e2',
    title: 'Lacquer & Light',
    name_vie: 'Sơn mài và Ánh sáng',
    name_en: 'Lacquer & Light',
    organizer: 'Tia-S Gallery',
    startDate: shiftIsoDate(-5),
    endDate: shiftIsoDate(20),
    location: 'Hoan Kiem, Hanoi',
    city: 'Hanoi',
    district: 'Hoan Kiem',
    lat: 21.0285,
    lng: 105.8542,
    imageUrl: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=1200',
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=1200' },
      { type: 'image', url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=1200' },
    ],
    description:
      'Masterworks in traditional son mai by contemporary Hanoi artists. Exploring the interplay between heavy resin and incandescent gold leaf.',
    category: 'exhibition',
    art_medium: 'Lacquer',
    event_type: 'Ongoing Show',
    place_type: 'Gallery',
    is_free: true,
    tags: ['free', 'hanoi', 'craft'],
    address: '24 Quang Trung, Hoan Kiem, Hanoi',
    google_map_link: 'https://maps.google.com/?q=24+Quang+Trung+Hoan+Kiem+Hanoi',
    saved_count: 74,
    moderation_status: 'approved',
  },
  {
    id: 'e3',
    title: 'Urban Fragments',
    name_vie: 'Mảnh vụn Đô thị',
    name_en: 'Urban Fragments',
    organizer: 'Sàn Art',
    startDate: todayIso(),
    endDate: shiftIsoDate(15),
    location: 'Binh Thanh, Ho Chi Minh City',
    city: 'Ho Chi Minh City',
    district: 'Binh Thanh',
    lat: 10.7937,
    lng: 106.7025,
    imageUrl: 'https://images.unsplash.com/photo-1518998053502-53cc83e9ce38?auto=format&fit=crop&q=80&w=1200',
    media: [
      { type: 'video', url: 'https://assets.mixkit.co/videos/preview/mixkit-walking-through-a-modern-art-gallery-4458-large.mp4' },
      { type: 'image', url: 'https://images.unsplash.com/photo-1494948141550-256616053995?auto=format&fit=crop&q=80&w=1200' },
    ],
    description:
      'A multi-media exhibition exploring the changing face of Saigon through large-scale sculpture and interactive silk installations.',
    category: 'exhibition',
    art_medium: 'Mixed Media',
    event_type: 'Exhibition',
    place_type: 'Art Space',
    tags: ['installation', 'saigon', 'featured'],
    address: '3 Me Linh, Binh Thanh, Ho Chi Minh City',
    google_map_link: 'https://maps.google.com/?q=3+Me+Linh+Binh+Thanh+Ho+Chi+Minh+City',
    saved_count: 86,
    featured: true,
    moderation_status: 'approved',
  },
  {
    id: 'e4',
    title: 'Soft Bodies / Hard City',
    name_vie: 'Cơ thể mềm / Thành phố cứng',
    organizer: 'The Factory Contemporary Arts Centre',
    startDate: shiftIsoDate(3),
    endDate: shiftIsoDate(35),
    location: 'Thu Duc, Ho Chi Minh City',
    city: 'Ho Chi Minh City',
    district: 'Thu Duc',
    lat: 10.8018,
    lng: 106.7425,
    imageUrl: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&q=80&w=1200',
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1459908676235-d5f02a50184b?auto=format&fit=crop&q=80&w=1200' },
    ],
    description:
      'An intergenerational group show on memory, labor, and architecture, pairing painting, textile work, and sculptural interventions.',
    category: 'exhibition',
    art_medium: 'Mixed Media',
    event_type: 'Exhibition Opening',
    place_type: 'Contemporary Art Center',
    is_free: true,
    registration_required: true,
    registration_link: 'https://example.com/register-soft-bodies-hard-city',
    tags: ['opening', 'group show', 'featured'],
    address: '15 Nguyen U Di, Thu Duc, Ho Chi Minh City',
    google_map_link: 'https://maps.google.com/?q=15+Nguyen+U+Di+Thu+Duc+Ho+Chi+Minh+City',
    saved_count: 68,
    featured: true,
    moderation_status: 'approved',
  },
  {
    id: 'e5',
    title: 'After the Rain: Performance Night',
    name_vie: 'Sau cơn mưa',
    organizer: 'Nha San Collective',
    startDate: shiftIsoDate(6),
    endDate: shiftIsoDate(6),
    location: 'Ba Dinh, Hanoi',
    city: 'Hanoi',
    district: 'Ba Dinh',
    lat: 21.0372,
    lng: 105.8292,
    imageUrl: 'https://images.unsplash.com/photo-1518998053502-53cc83e9ce38?auto=format&fit=crop&q=80&w=1200',
    description:
      'A one-night performance program bringing together movement, spoken word, and experimental sound from emerging artists.',
    category: 'performance',
    art_medium: 'Performance',
    event_type: 'Performance',
    place_type: 'Independent Space',
    is_free: false,
    price: 180000,
    registration_required: true,
    registration_link: 'https://example.com/after-the-rain',
    tags: ['performance', 'ticketed'],
    address: '462 Buoi, Ba Dinh, Hanoi',
    google_map_link: 'https://maps.google.com/?q=462+Buoi+Ba+Dinh+Hanoi',
    saved_count: 42,
    moderation_status: 'approved',
  },
  {
    id: 'e6',
    title: 'Da Nang Open Studios Weekend',
    name_vie: 'Cuối tuần Studio Mở Đà Nẵng',
    organizer: 'Da Nang Art Circle',
    startDate: shiftIsoDate(10),
    endDate: shiftIsoDate(12),
    location: 'Hai Chau, Da Nang',
    city: 'Da Nang',
    district: 'Hai Chau',
    lat: 16.0604,
    lng: 108.2234,
    imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=80&w=1200',
    description:
      'A city-wide weekend connecting artist studios, project spaces, and pop-up exhibitions with a suggested visitor route.',
    category: 'workshop',
    art_medium: 'Mixed Media',
    event_type: 'Workshop',
    place_type: 'Studio',
    is_free: true,
    tags: ['route', 'open studios', 'da nang'],
    address: 'Tran Phu, Hai Chau, Da Nang',
    google_map_link: 'https://maps.google.com/?q=Tran+Phu+Hai+Chau+Da+Nang',
    saved_count: 57,
    moderation_status: 'approved',
  },
  {
    id: 'e7',
    title: 'Collecting Contemporary Vietnam',
    name_vie: 'Sưu tầm Nghệ thuật Đương đại Việt Nam',
    organizer: 'Manzi',
    startDate: shiftIsoDate(4),
    endDate: shiftIsoDate(4),
    location: 'Ba Dinh, Hanoi',
    city: 'Hanoi',
    district: 'Ba Dinh',
    lat: 21.0315,
    lng: 105.8407,
    imageUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80&w=1200',
    description:
      'A public talk on buying art for the first time, preserving works, and supporting emerging Vietnamese artists without gallery intimidation.',
    category: 'talk',
    art_medium: 'Collecting',
    event_type: 'Talk',
    place_type: 'Cafe',
    is_free: true,
    registration_required: true,
    registration_link: 'https://example.com/collecting-contemporary-vietnam',
    tags: ['talk', 'beginners'],
    address: '14 Phan Huy Ich, Ba Dinh, Hanoi',
    google_map_link: 'https://maps.google.com/?q=14+Phan+Huy+Ich+Ba+Dinh+Hanoi',
    saved_count: 39,
    moderation_status: 'approved',
  },
  {
    id: 'e8',
    title: 'Video Rooms: New Moving Image',
    name_vie: 'Phòng Video',
    organizer: 'Virtual Art Room',
    startDate: shiftIsoDate(-2),
    endDate: shiftIsoDate(18),
    location: 'Online',
    city: 'Online',
    district: 'Virtual',
    lat: 10.7769,
    lng: 106.7009,
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=1200',
    description:
      'A rotating online screening room for new Vietnamese moving image work, with artist Q&As streamed weekly.',
    category: 'exhibition',
    art_medium: 'Video Art',
    event_type: 'Online Screening',
    place_type: 'Virtual',
    is_virtual: true,
    is_free: true,
    tags: ['virtual', 'video art'],
    registration_link: 'https://example.com/video-rooms',
    saved_count: 63,
    moderation_status: 'approved',
  },
  {
    id: 'e9',
    title: 'Mekong Material Futures',
    name_vie: 'Tương lai Vật liệu Mekong',
    organizer: 'Can Tho Art Lab',
    startDate: shiftIsoDate(8),
    endDate: shiftIsoDate(28),
    location: 'Ninh Kieu, Can Tho',
    city: 'Can Tho',
    district: 'Ninh Kieu',
    lat: 10.0342,
    lng: 105.7882,
    imageUrl: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&q=80&w=1200',
    description:
      'Artists and makers working with bamboo, fabric, and river waste materials reimagine local craft through contemporary installation.',
    category: 'exhibition',
    art_medium: 'Installation',
    event_type: 'Exhibition',
    place_type: 'Community Space',
    is_free: true,
    tags: ['mekong', 'installation', 'free'],
    address: '48 Hai Ba Trung, Ninh Kieu, Can Tho',
    google_map_link: 'https://maps.google.com/?q=48+Hai+Ba+Trung+Ninh+Kieu+Can+Tho',
    saved_count: 29,
    moderation_status: 'approved',
  },
  {
    id: 'e10',
    title: 'Auction for Atelier Support',
    name_vie: 'Đấu giá Hỗ trợ Xưởng nghệ sĩ',
    organizer: 'Judooo Pilot',
    startDate: shiftIsoDate(12),
    endDate: shiftIsoDate(13),
    location: 'District 3, Ho Chi Minh City',
    city: 'Ho Chi Minh City',
    district: 'District 3',
    lat: 10.7867,
    lng: 106.6881,
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=1200',
    description:
      'A small-format benefit auction supporting affordable studio production grants for emerging artists in Ho Chi Minh City.',
    category: 'auction',
    art_medium: 'Mixed Media',
    event_type: 'Auction',
    place_type: 'Pop-up Venue',
    is_free: false,
    price: 250000,
    registration_required: true,
    registration_link: 'https://example.com/atelier-support-auction',
    tags: ['auction', 'benefit'],
    address: '26 Vo Van Tan, District 3, Ho Chi Minh City',
    google_map_link: 'https://maps.google.com/?q=26+Vo+Van+Tan+District+3+Ho+Chi+Minh+City',
    saved_count: 47,
    moderation_status: 'approved',
  },
];
