-- Bilingual event and artwork content columns.
-- Safe to run multiple times.

alter table if exists public.events
  add column if not exists name_vie text,
  add column if not exists name_en text,
  add column if not exists description_vie text,
  add column if not exists description_en text,
  add column if not exists art_medium text,
  add column if not exists art_medium_vie text,
  add column if not exists art_medium_en text,
  add column if not exists event_type text,
  add column if not exists event_type_vie text,
  add column if not exists event_type_en text,
  add column if not exists place_type text,
  add column if not exists place_type_vie text,
  add column if not exists place_type_en text,
  add column if not exists district text,
  add column if not exists city_vie text,
  add column if not exists city_en text,
  add column if not exists district_vie text,
  add column if not exists district_en text,
  add column if not exists address_vie text,
  add column if not exists address_en text,
  add column if not exists is_virtual boolean,
  add column if not exists is_free boolean,
  add column if not exists tags text[] default '{}',
  add column if not exists price numeric(14,2),
  add column if not exists registration_required boolean,
  add column if not exists registration_link text,
  add column if not exists google_map_link text,
  add column if not exists socialvideo_url text,
  add column if not exists moderation_status moderation_state,
  add column if not exists submitter_name text,
  add column if not exists submitter_email text,
  add column if not exists submitter_organization text;

alter table if exists public.artworks
  add column if not exists title_vie text,
  add column if not exists title_en text,
  add column if not exists description_vie text,
  add column if not exists description_en text,
  add column if not exists medium_vie text,
  add column if not exists medium_en text,
  add column if not exists style_vie text,
  add column if not exists style_en text,
  add column if not exists city_vie text,
  add column if not exists city_en text,
  add column if not exists country_vie text,
  add column if not exists country_en text,
  add column if not exists provenance_vie text,
  add column if not exists provenance_en text,
  add column if not exists authenticity_vie text,
  add column if not exists authenticity_en text,
  add column if not exists condition_report_vie text,
  add column if not exists condition_report_en text,
  add column if not exists story_vie text,
  add column if not exists story_en text,
  add column if not exists moderation_status moderation_state;
